// default package
// Generated Feb 27, 2023, 5:09:25 PM by Hibernate Tools 6.0.0.Alpha3


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userreviewproduct generated by hbm2java
 */
@Entity
@Table(name="userreviewproduct"
    ,catalog="marketplacedb"
)
public class Userreviewproduct  implements java.io.Serializable {


     private UserreviewproductId id;
     private Product product;
     private User user;
     private Integer noStars;
     private String comment;

    public Userreviewproduct() {
    }

	
    public Userreviewproduct(UserreviewproductId id, Product product, User user) {
        this.id = id;
        this.product = product;
        this.user = user;
    }
    public Userreviewproduct(UserreviewproductId id, Product product, User user, Integer noStars, String comment) {
       this.id = id;
       this.product = product;
       this.user = user;
       this.noStars = noStars;
       this.comment = comment;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="userId", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="productId", nullable=false) ) } )
    public UserreviewproductId getId() {
        return this.id;
    }
    
    public void setId(UserreviewproductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productId", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="noStars")
    public Integer getNoStars() {
        return this.noStars;
    }
    
    public void setNoStars(Integer noStars) {
        this.noStars = noStars;
    }

    
    @Column(name="comment", length=510)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


