package iti.jets.repo.entities;
// default package
// Generated Feb 27, 2023, 5:09:25 PM by Hibernate Tools 6.0.0.Alpha3


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UserorderproductId generated by hbm2java
 */
@Embeddable
public class UserorderproductId  implements java.io.Serializable {


     private int userId;
     private int productId;

    public UserorderproductId() {
    }

    public UserorderproductId(int userId, int productId) {
       this.userId = userId;
       this.productId = productId;
    }
   


    @Column(name="userId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="productId", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserorderproductId) ) return false;
		 UserorderproductId castOther = ( UserorderproductId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


